- module: mysql
  error:
    enabled: true
    var.paths:
      - /var/lib/mysql/mysql-error.*
    input:
      close_removed: true
      close_renamed: false

  slowlog:
    enabled: true
    var.paths:
      - /var/lib/mysql/mysql-slow.*
    input:
      close_removed: true
      close_renamed: false
